# ./docker-compose.yaml
version: "3.8"
services:
  api:
    container_name: api
    build:
      context: ./api/
    tty: true
    ports:
      - "8080:8080"
    env_file:
      - ./db/.env
    volumes:
      - type: bind
        source: "./api"
        target: "/api"
    
  frontend:
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: "./frontend"
        target: "/app"
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
  
  mysql:
    container_name: mysql
    platform: linux/amd64
    build:
      context: ./db/
    ports:
      - "3306:3306"
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    restart: always
    volumes:
      - type: volume
        source: db_store
        target: /var/lib/mysql

volumes:
  db_store: